In [1]:
import tensorflow as tf
import torch 

In [2]:
def _independent_straight_through_sampling(rationale_logits):
    """
    Straight through sampling.
    Outputs:
        z -- shape (batch_size, sequence_length, 2)        
    """
    z = tf.nn.softmax(rationale_logits)
    z_hard = tf.cast(tf.equal(z, tf.reduce_max(z, -1, keep_dims=True)),
                     z.dtype)
    z = tf.stop_gradient(z_hard - z) + z

    return z

In [4]:
rationale_logits = [
    [0.9, 0.1],
    [0.8, 0.2],
    [0.7, 0.3]
]
rationale_logits = torch.tensor(rationale_logits)
z = torch.nn.functional.softmax(rationale_logits)
print(z)
print("\n")
reduce_max = torch.max(z, dim = 1, keepdim=False).values.reshape(-1,1)
print(reduce_max)
equal = z.eq(reduce_max)
z_hard = equal.type(torch.FloatTensor)
z_soft = (z_hard - z).detach_() + z
print(z_soft)

tensor([[0.6900, 0.3100],
        [0.6457, 0.3543],
        [0.5987, 0.4013]])


tensor([[0.6900],
        [0.6457],
        [0.5987]])
tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


<ipython-input-4-2a0d3a285849>:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  z = torch.nn.functional.softmax(rationale_logits)


In [26]:
rationale_logits.shape

torch.Size([3, 2])

In [29]:
weight = torch.tensor([1,0])

In [30]:
rationale_logits*weight

tensor([[0.9000, 0.0000],
        [0.8000, 0.0000],
        [0.7000, 0.0000]])

In [6]:
import numpy as np
X = np.array([1,2,3,4,5,6,7,8,9])
Y = torch.tensor(X)
index_ = [1,4,6]
X[index_], Y[index_]

(array([2, 5, 7]), tensor([2, 5, 7]))

In [8]:
from torch.autograd import Variable


In [11]:
Variable(torch.tensor([1]*10), requires_grad=True)

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [14]:
W = torch.nn.Parameter(torch.randn(5))
W.requires_grad = True

In [15]:
W

Parameter containing:
tensor([ 0.0492, -0.2416, -0.4058,  1.7760,  0.9588], requires_grad=True)

In [16]:
1.3219*0.67

0.8856730000000002